include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/**
    - lib/data/**
    - lib/presentation/**
    - lib/providers/**
    - lib/services/**
    - test/**
    - integration_test/**
    - ai_engine/**

linter:
  rules:
    avoid_print: true
