name: ecoc
description: EcoC speech-to-text companion for Bluetooth smart glasses
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_blue_plus: ^2.2.1
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
