name: Flutter Build APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Fixed version for Flutter 3.x

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # Fixed stable version

      - name: Fix Permissions
        run: chmod +x android/gradlew

      - name: Clean & Build
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
